const APP_CONSTANTS = {
    ADD_EDIT_TITLE : ' an Item',
    CANCEL : 'Cancel',
    OR_ADD_INSTEAD : 'Or add a recipe instead.',
    NAME_HINT : "Item Name (required)",
    COUNT_HINT : "Amount",
    MEASURE_HINT : "Measurment (ex. cans)",
    NOTE_HINT : "Notes",
    USERNAME_HINT : 'Username',
    PASSWORD_HINT : 'Password',
    RECIPE_NAME_HINT : "Enter a recipe name",
    CODE_HINT : "Enter the join code",
    FAMILY_HINT : 'Join a family',
    CREATE_FAMILY_HINT : 'Create a family',
    ENTER_FAMILY_HINT : 'Enter a family name',
    IS_NOTE : 'Is note item?',
    IS_STANDARD : 'Is standard item?',
    LOGIN : 'Login',
    REGISTER : 'Register',
    LOGOUT : 'Logout',
    ADD : 'Add',
    EDIT : 'Edit',
    NEW_TO_APP : 'New to Grocery List? ',
    ALREADY_ACCOUNT : 'Already have an account? ',
    ARE_YOU_SURE : 'Are you sure?',
    LEAVE_FAMILY: 'Leave Family',
    FAMILY_JOIN : 'Your Families',
    OK : 'Ok',
    FINISHED_FOR_NOW : 'All finished shopping for now!\n Check later for new items',
    NO_RECIPES : 'You have no recipes added!',
    QUESTION : '?',
    INCLUDE : 'Include',
    SPACE : ' ',
    DELETE : 'Delete',
    CREATE : 'Create',
    RECIPES : 'Recipes',
    YOUR_RECIPES : 'Your Recipes',
    FAMILY_RECIPES : 'Family Recipes',
    ADD_A_RECIPE : 'Add a recipe',
    HELP : 'Found on main page of a registered member',
    HELP_INFO : 'Create or join a family under the family icon.',
    NEW : 'New? ',
    JOIN : 'Join',
    RETURNING : 'Returning? ',
    EMAIL_HINT : 'Email',

}

export default APP_CONSTANTS;